Feat/aset usaha
WorldieATW/worldie-backend pull request #44
Opened 2023-11-30 17:13 UTC by aidahputri

All endpoints #6

2023-12-01 04:10 UTC, bonaventuragal commented on src/aset-usaha/aset-usaha.controller.ts
> +  @Patch('update/accomodation/:id')
ini juga ya

2023-12-01 04:20 UTC, bonaventuragal requested changes
function ini bisa diubah pake spread operator biar ga panjang. function lain yang serupa juga mendingan disamain

2023-12-01 04:20 UTC, bonaventuragal commented on src/repository/asetUsaha.repository.ts
> +    { nama, deskripsi, harga, imgUrl, jenisKendaraan }: KendaraanDTO,
```suggestion
    dto: KendaraanDTO,
```

2023-12-01 13:58 UTC, rifqifarelmuhammad commented on src/aset-usaha/aset-usaha.DTO.ts
> +  @IsNotEmpty()
ini yg isNotEmpty benar kah? Berarti di paramnya wajib kudu mesti ada imgUrl, jalan, kota, provinsi, dan negara?

2023-12-01 13:58 UTC, rifqifarelmuhammad commented on src/aset-usaha/aset-usaha.controller.ts
> +  @Patch('update/tourist-attraction/:id')
setuju

2023-12-01 13:58 UTC, rifqifarelmuhammad commented on src/aset-usaha/aset-usaha.controller.ts
>        responseData
ditto

2023-12-01 13:58 UTC, rifqifarelmuhammad commented on src/aset-usaha/aset-usaha.service.ts
> +    if (user.role !== 'AGEN') {
ditto

2023-12-01 13:58 UTC, rifqifarelmuhammad commented on src/aset-usaha/aset-usaha.service.ts
> +    if (user.role !== 'AGEN') {
ditto

2023-12-01 13:58 UTC, rifqifarelmuhammad commented on src/repository/asetUsaha.repository.ts
> +    { nama, deskripsi, harga, imgUrl, jenisKendaraan }: KendaraanDTO,
imo masih oke untuk didestructure deh

2023-12-01 13:58 UTC, rifqifarelmuhammad commented on src/repository/asetUsaha.repository.ts
> +        tipe: 'DESTINASI_WISATA',
g perlu, masukin yg memang perlu diubah aja

2023-12-02 10:57 UTC, aidahputri commented on src/aset-usaha/aset-usaha.DTO.ts
> +  @IsNotEmpty()
hooh, gue mikirnya itu informasi penting buat aset usaha, kaya gimana traveler bisa tertarik kalo gaada gambar dan alamat lengkapnya wkwkwk

2023-12-02 14:22 UTC, bonaventuragal approved these changes

2023-12-02 14:24 UTC, merged